### ISSUE TITLE
[docker]非正常关机后，直接运行节点恢复脚本有可能使得app的container无法被拉起

### ISSUE THREAD

**Issue by cloudfly** [laincloud/lain#1]
tinydns drift到node2后，强行断电重启，

container无法被正常拉起，原因为network信息没有及时反注册

`service endpoint with name tinydns.worker.worker.v0-i1-d1 already exists`

**Comment by panli889** [comment]
如果某个节点非正常关机，deployd 会尝试在其他节点中重新拉起坏掉节点中的容器，并且赋予之前的IP。由于节点关机的时候 endpoint 信息没有回收，IP 地址也没有回收，会出现错误，主要的错误信息包括：
- service endpoint already exists
- IP address already been used

可以通过在主节点上运行 `lainctl network recover -n {nodename} -t {appname} -c {procname} -i {instance_no}`  指定回收坏掉节点上应用的某个proc实例的网络信息；
