### ISSUE TITLE
如果需要为 lain.yaml 的 proc 增加一个配置项，需要修改哪几个组件

### ISSUE THREAD

**Issue by rmrf** [laincloud/lain#106]
类似 web proc 中 https_only 这样的一个选项，我目前已经修改了 lain-sdk  ， etcd 中 /lain/console/apps/<web_app_name> 已经可以看到这个新增的配置项。但 lainlet 查询 webproc的时候看不到这个它， 也就是说pod_group 中 这个配置项是没有的。

我还需修改哪个组件才能实现让 lainlet 的 webrouter/webprocs 查询到它？

谢谢！

**Comment by rmrf** [comment]
@panli889

**Comment by panli889** [comment]
@rmrf 如果 lain-sdk 解析的时候是放在 annotation 项里的话，直接 lainlet 的 webrouter/webprocs 接口应该是能够查询到的。console 内部依赖的 lain-sdk 已经更新了么？

**Comment by rmrf** [comment]
@panli889 好问题，我才注意到 console 对 lain-sdk有依赖，我更新一下试试。

**Comment by panli889** [comment]
@rmrf 恩，console 对 lain.yaml 的解析有依赖 lain-sdk
