### ISSUE TITLE
bootstrap failed

### ISSUE THREAD

**Issue by itxx00** [laincloud/lain#109]
TASK: [bootstrap-docker | pull images if not exists (use --saved-images option if your connection to DockerHub is very slow)] ***
2017-03-25 23:23:47.063600 (last task costs 0:00:00.126972)
ok: [bootstrap-node] => (item=deployd:2.0.3)
ok: [bootstrap-node] => (item=pip-binary:1472205565)
ok: [bootstrap-node] => (item=webrouter:release-1488176768-e44c5d3953f6fc634adbc8afedb80032eaea1024)
ok: [bootstrap-node] => (item=lvault:meta-1485154203-73072c92b1862ab470b8d872b278f734747b0739)
ok: [bootstrap-node] => (item=lvault:release-1485154203-73072c92b1862ab470b8d872b278f734747b0739)
ok: [bootstrap-node] => (item=registry:meta-1472106576-30f4071d4bdc3ed6d0cb3c34ea9047ec6c098e57)
ok: [bootstrap-node] => (item=rebellion:2.0.4)
ok: [bootstrap-node] => (item=calico_node:v0.19.0)
ok: [bootstrap-node] => (item=lainlet:2.0.2)
ok: [bootstrap-node] => (item=tinydns:meta-1488166191-27429fccba819c796bb7c92b1c4bb7b48cda2406)
failed: [bootstrap-node] => (item=swarm:1.2.5) => {"failed": true, "item": "swarm:1.2.5", "parsed": false}

Pulling repository registry.aliyuncs.com/laincloud/swarm
Error: No such image, container or task: swarm:1.2.5
Error: image laincloud/swarm:1.2.5 not found
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1490455428.14-187555272493902/docker_pull_image", line 1671, in <module>
    main()
  File "/root/.ansible/tmp/ansible-tmp-1490455428.14-187555272493902/docker_pull_image", line 24, in main
    check_call(['docker', 'pull', src_image])
  File "/usr/lib64/python2.7/subprocess.py", line 542, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['docker', 'pull', 'registry.aliyuncs.com/laincloud/swarm:1.2.5']' returned non-zero exit status 1

ok: [bootstrap-node] => (item=tinydns:release-1488166191-27429fccba819c796bb7c92b1c4bb7b48cda2406)
ok: [bootstrap-node] => (item=registry:release-1472106576-30f4071d4bdc3ed6d0cb3c34ea9047ec6c098e57)
ok: [bootstrap-node] => (item=networkd-binary:0.1.17)
ok: [bootstrap-node] => (item=backupctl:meta-1460534637-7bb87af249b1672e18baacbacb6d3ffd6155e81c)
ok: [bootstrap-node] => (item=calico_node-libnetwork:v0.8.0)
ok: [bootstrap-node] => (item=console:release-1472205460-202274370db1b57cbdd18b89174ad449a9b25024)
ok: [bootstrap-node] => (item=webrouter:meta-1488176768-e44c5d3953f6fc634adbc8afedb80032eaea1024)
ok: [bootstrap-node] => (item=backupctl:release-1460534637-7bb87af249b1672e18baacbacb6d3ffd6155e81c)
ok: [bootstrap-node] => (item=console:meta-1472205460-202274370db1b57cbdd18b89174ad449a9b25024)

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/root/bootstrap.yaml.retry

**Comment by itxx00** [comment]
@panli889  能否帮忙看看是什么问题？谢谢

**Comment by panli889** [comment]
@itxx00 看错误信息是 swarm image 不存在，目前我本地 pull 是可以的，可否再试下呢？

**Comment by itxx00** [comment]
重试了几次可以了，网络慢导致下载不成功，感谢！
