### ISSUE TITLE
怎么判断当前网络环境有没有限制数据包的来源IP

### ISSUE THREAD

**Issue by liuxu623** [laincloud/lain#122]
# 如果 VPC 限制了数据包的来源 IP（如阿里云）
sudo ./bootstrap -r registry.aliyuncs.com/laincloud --ipip

**Comment by frostynova** [comment]
找两台机器 A B，它们的内网 ip 分别为 $a $b，测试用的新 ip 分别为：172.16.2.3 和 172.16.2.4
```
A: 
ip addr add 172.16.2.3/24 dev eth0
ip route add 172.16.2.4/32 via $b

B:
ip addr add 172.16.2.4/24 dev eth0
ip route add 172.16.2.3/32 via $a
```
如果在 A 或 B 上能 ping 通对方的测试 ip 那么就是没有做源地址校验

**Comment by liuxu623** [comment]
Thank you.
