### ISSUE TITLE
Bootstrap 之前对机器进行clear操作

### ISSUE THREAD

**Issue by cloudfly** [laincloud/lain#14]
bootstrap 前要对所有 Lain 相关的组件做清理操作。来保证 bootstrap 在重复跑的时也能成功。

现在 bootstrap 是不可重复跑的，若失败了，只能重装系统才能再跑，对于非虚拟机用户，这是不可接受的。

**Comment by ericpai** [comment]
Things to be cleaned
1. Containers
2. Data in Etcd
3. Configurations of Services: swarm-manager, swarm-agent, backupd, lainlet, deployd, rebellion
