### ISSUE TITLE
document for mountpoint

### ISSUE THREAD

**Issue by sunyi00** [laincloud/lain#18]

**Comment by sunyi00** [comment]
@panli889 给 mountpoint 机制的具体文档咱们好像缺失了，写在  白皮书 的 /usermanual/lainyaml/mountpoint 吧 ，辛苦

**Comment by panli889** [comment]
fixed at https://github.com/laincloud/white-paper/commit/9d37c7ec62417e8197f7ceebc6d2047551083232.
