### ISSUE TITLE
Does lain support Ubuntu?

### ISSUE THREAD

**Issue by yuyang0** [laincloud/lain#206]
The install instruction said lain depends on Centos, but my production environment is ubuntu, so it is possible to run lain on ubuntu?

**Comment by wchaoyi** [comment]
目前不支持，将来有可能支持。欢迎提 pr ～～

**Comment by yuyang0** [comment]
工作量大不大呢？ 主要哪些地方需要调整？

**Comment by fossilet** [comment]
有一些工作量，你在这个仓库里面搜索yum，首先得把这些包换成Ubuntu的，包括配置。你们要有时间可以试试，我们提供协助。

**Comment by yuyang0** [comment]
lain有没有在生产环境大规模部署呢？还有有没有关于lain的架构的设计文档？

**Comment by fossilet** [comment]
我们部门的服务都在LAIN上运行，文档见http://docs.laincloud.com。

**Comment by yuyang0** [comment]
我打算移植到ubuntu试一试，有问题再向你们请教

**Comment by yuyang0** [comment]
@fossilet 能给个邮件或者微信吗？有点问题想请教下

**Comment by fossilet** [comment]
@yuyang0 已经发邮件。
