### ISSUE TITLE
CentOS 7 predictable network interface name 导致的 `vagrant up node1` 和 `add node` 失败

### ISSUE THREAD

**Issue by kaizhang-shanxi** [laincloud/lain#75]
# 起因

因为 CentOS 7 采用了 [predictable network interface name](https://www.freedesktop.org/wiki/Software/systemd/PredictableNetworkInterfaceNames/)，导致两个问题：
1. 网卡名和 `/etc/sysconfig/network-scripts/ifcfg-*` 的名字不匹配，所以 `vagrant up node1` 失败；
2. lain 默认寻找 `eth1` 作为 `node1` 的网卡，找不到则使用默认网卡；新命名方式使用 `enp0s8` 这样的名字，没有了 `eth1`；在 vagrant 里默认 IP 是 `10.0.2.15`，而这个 IP 是用来实现虚拟机之间的通信的，从外部不可访问，所以 node2 里的 etcd 访问不了 node1 里的 etcd；所以 `add node` 失败。

# 经过

为了解决这个问题，我将 [chef/bento](https://github.com/chef/bento) 与 [flex 的版本](https://github.com/frostynova/bento) 合并了起来~

## 与 [flex 版本](https://github.com/frostynova/bento) 的不同

合并了 [chef/bento](https://github.com/chef/bento) Fix new-style device naming from Network Manager on RHEL/CentOS 7 的[修改](https://github.com/chef/bento/commit/d0c2e56fcc4ec81e152af6c5fbdf1f115f976e95)。

## 与 [chef/bento](https://github.com/chef/bento) 的不同

合并了 wzyboy [对 Predictable Network Interface Names 的禁用](https://github.com/frostynova/bento/commit/b46b34c149ce3bbafddaf27e7e2172855a7f5f33)。

## 打包过程

```
git clone https://github.com/kaizhang-shanxi/bento  # 下载打包程序

# 需要一个 centos 的 dvd
brew install packer   # 当时 flex 的步骤，但我忘了是不是必需的了。。。

cd bento
bin/bento build  -m file:///Users/flex/Soft/ISO/ centos-lain-7.2-x86_64.json
```

> **重要**：是 `centos-lain-7.2-x86_64.json`，不是 `centos-7.2-x86_64.json`。

# 结果

经测试：
+ `vagrant up node1` 成功；
+ `sudo ./bootstrap -r registry.aliyuncs.com/laincloud --vip=192.168.77.201` 成功；
+ `vagrant up node2` 成功；
+ `sudo lainctl node add -p playbooks -q node2:192.168.77.22` 成功。

@sunyi00

**Comment by sunyi00** [comment]
@kaizhang-shanxi 昨天晚上已在 Hashicorp 上传和 release 了 vagrant 的 centos-lain v1470066786 新版本，麻烦验证一下？

**Comment by kaizhang-shanxi** [comment]
多谢毅总~我晚上验证一下，可以么？因为白天要用昨天起的 lain 集群跑一下程序~ @sunyi00

**Comment by sunyi00** [comment]
@kaizhang-shanxi 客气。没问题呀，并不着急。

**Comment by kaizhang-shanxi** [comment]
ok~ @sunyi00

**Comment by kaizhang-shanxi** [comment]
经测试：
+ `vagrant up node1` 成功；
+ `sudo ./bootstrap -r registry.aliyuncs.com/laincloud --vip=192.168.77.201` 成功；
+ `vagrant up node2` 成功；
+ `sudo lainctl node add -p playbooks -q node2:192.168.77.22` 成功；
+ `vagrant up node3` 成功；
+ `sudo lainctl node add -p playbooks -q node3:192.168.77.23` 成功；
+ `sudo lainctl node remote -p playbooks node2` 成功。

@sunyi00
